### ISSUE TITLE
samtoools merge crashing, failing pipeline

### ISSUE THREAD

**Issue by mbassalbioinformatics** [sdparekh/zUMIs#202]
**Describe the bug**
When running zUMIs 2.9.3b on an InDrop V3 library, the code gets to the samtools merge step and fails.  Ive tried it with a 2.9.2 and 2.9.3a also but still the same issue.  Also the preceding demultiplex step produces an incredibly large number of files, not sure why exactly.  

**To Reproduce**
YAML - file and folder names trimmed for brevity only.
project: zumis_180430_30dVhl123
sequence_files:
  file1:
    name: ...._R1_001.fastq.gz
    base_definition: cDNA(1-50)
  file2:
    name: .....R2_001.fastq.gz
    base_definition: BC(1-8)
  file3:
    name: ....._R3_001.fastq.gz
    base_definition: BC(1-6)
  file4:
    name: ...._R4_001.fastq.gz
    base_definition:
    - BC(1-8)
    - UMI(9-14)
reference:
  STAR_index: ...../star_2.7.3a/
  GTF_file: ......../genes.gtf
  additional_STAR_params: ''
  additional_files: ~
out_dir: ......./zumis_180430_30dVhl123
num_threads: 20
mem_limit: 0
filter_cutoffs:
  BC_filter:
    num_bases: 1
    phred: 20
  UMI_filter:
    num_bases: 1
    phred: 20
barcodes:
  barcode_num: ~
  barcode_file: ~
  automatic: yes
  BarcodeBinning: 1
  nReadsperCell: 100
counting_opts:
  introns: yes
  downsampling: '0'
  strand: 0
  Ham_Dist: 1
  velocyto: yes
  primaryHit: yes
  twoPass: yes
make_stats: yes
which_Stage: Counting
Rscript_exec: Rscript
STAR_exec: STAR
pigz_exec: pigz
samtools_exec: samtools

Using miniconda environment for zUMIs!
 note: internal executables will be used instead of those specified in the YAML file!

 You provided these parameters:
 YAML file:	zumis_180430_30dVhl123.yaml
 zUMIs directory:		/home/mbassal/tools/zUMIs-2.9.3
 STAR executable		STAR
 samtools executable		samtools
 pigz executable		pigz
 Rscript executable		Rscript
 RAM limit:   0
 zUMIs version 2.9.3b 

Terminal Output:

Wed Jul 22 03:51:29 EDT 2020
WARNING: The STAR version used for mapping is 2.7.3a and the STAR index was created using the version 2.7.1a. This may lead to an error while mapping. If you encounter any errors at the mapping stage, please make sure to create the STAR index using STAR 2.7.3a.
Counting...
[1] "2020-07-22 03:51:38 EDT"
[1] "1.5e+08 Reads per chunk"
[1] "Loading reference annotation from:"
[1] "/mnt/md0/MB/analyses/lev_mouse/Pipeline/09_rna_kinetics/velocyto/kp/zumis_180430_30dVhl123/zumis_180430_30dVhl123.final_annot.gtf"
[1] "Annotation loaded!"
Warning message:
`as_quosure()` requires an explicit environment as of rlang 0.3.0.
Please supply `env`.
This warning is displayed once per session. 
[1] "Assigning reads to features (ex)"

        ==========     _____ _    _ ____  _____  ______          _____  
        =====         / ____| |  | |  _ \|  __ \|  ____|   /\   |  __ \ 
          =====      | (___ | |  | | |_) | |__) | |__     /  \  | |  | |
            ====      \___ \| |  | |  _ <|  _  /|  __|   / /\ \ | |  | |
              ====    ____) | |__| | |_) | | \ \| |____ / ____ \| |__| |
        ==========   |_____/ \____/|____/|_|  \_\______/_/    \_\_____/
       Rsubread 1.32.4

//========================== featureCounts setting ===========================\\
||                                                                            ||
||             Input files : 1 BAM file                                       ||
||                           S zumis_180430_30dVhl123.filtered.tagged.Ali ... ||
||                                                                            ||
||              Annotation : R data.frame                                     ||
||      Assignment details : <input_file>.featureCounts.bam                   ||
||                      (Note that files are saved to the output directory)   ||
||                                                                            ||
||      Dir for temp files : .                                                ||
||                 Threads : 20                                               ||
||                   Level : meta-feature level                               ||
||              Paired-end : yes                                              ||
||      Multimapping reads : counted                                          ||
||     Multiple alignments : primary alignment only                           ||
|| Multi-overlapping reads : not counted                                      ||
||   Min overlapping bases : 1                                                ||
||                                                                            ||
||          Chimeric reads : not counted                                      ||
||        Both ends mapped : not required                                     ||
||                                                                            ||
\\===================== http://subread.sourceforge.net/ ======================//

//================================= Running ==================================\\
||                                                                            ||
|| Load annotation file .Rsubread_UserProvidedAnnotation_pid7916 ...          ||
||    Features : 254044                                                       ||
||    Meta-features : 31053                                                   ||
||    Chromosomes/contigs : 41                                                ||
||                                                                            ||
|| Process BAM file zumis_180430_30dVhl123.filtered.tagged.Aligned.out.ba ... ||
||    Single-end reads are included.                                          ||
||    Assign alignments to features...                                        ||
||    Total alignments : 248241666                                            ||
||    Successfully assigned alignments : 121320178 (48.9%)                    ||
||    Running time : 3.09 minutes                                             ||
||                                                                            ||
||                                                                            ||
\\===================== http://subread.sourceforge.net/ ======================//

[1] "Assigning reads to features (in)"

        ==========     _____ _    _ ____  _____  ______          _____  
        =====         / ____| |  | |  _ \|  __ \|  ____|   /\   |  __ \ 
          =====      | (___ | |  | | |_) | |__) | |__     /  \  | |  | |
            ====      \___ \| |  | |  _ <|  _  /|  __|   / /\ \ | |  | |
              ====    ____) | |__| | |_) | | \ \| |____ / ____ \| |__| |
        ==========   |_____/ \____/|____/|_|  \_\______/_/    \_\_____/
       Rsubread 1.32.4

//========================== featureCounts setting ===========================\\
||                                                                            ||
||             Input files : 1 BAM file                                       ||
||                           S zumis_180430_30dVhl123.filtered.tagged.Ali ... ||
||                                                                            ||
||              Annotation : R data.frame                                     ||
||      Assignment details : <input_file>.featureCounts.bam                   ||
||                      (Note that files are saved to the output directory)   ||
||                                                                            ||
||      Dir for temp files : .                                                ||
||                 Threads : 20                                               ||
||                   Level : meta-feature level                               ||
||              Paired-end : yes                                              ||
||      Multimapping reads : counted                                          ||
||     Multiple alignments : primary alignment only                           ||
|| Multi-overlapping reads : not counted                                      ||
||   Min overlapping bases : 1                                                ||
||                                                                            ||
||          Chimeric reads : not counted                                      ||
||        Both ends mapped : not required                                     ||
||                                                                            ||
\\===================== http://subread.sourceforge.net/ ======================//

//================================= Running ==================================\\
||                                                                            ||
|| Load annotation file .Rsubread_UserProvidedAnnotation_pid7916 ...          ||
||    Features : 203221                                                       ||
||    Meta-features : 25397                                                   ||
||    Chromosomes/contigs : 38                                                ||
||                                                                            ||
|| Process BAM file zumis_180430_30dVhl123.filtered.tagged.Aligned.out.ba ... ||
||    Single-end reads are included.                                          ||
||    Assign alignments to features...                                        ||
||    Total alignments : 248241666                                            ||
||    Successfully assigned alignments : 20285497 (8.2%)                      ||
||    Running time : 1.66 minutes                                             ||
||                                                                            ||
||                                                                            ||
\\===================== http://subread.sourceforge.net/ ======================//

[1] "2020-07-22 03:57:52 EDT"
[1] "Coordinate sorting intermediate bam file..."
[bam_sort_core] merging from 0 files and 20 in-memory blocks...
[1] "2020-07-22 04:07:45 EDT"
[1] "Hamming distance collapse in barcode chunk 1 out of 2"
[1] "Splitting data for multicore hamming distance collapse..."
[1] "Setting up multicore cluster & generating molecule mapping tables ..."
[1] "Finished multi-threaded hamming distances"
[1] "Hamming distance collapse in barcode chunk 2 out of 2"
[1] "Splitting data for multicore hamming distance collapse..."
[1] "Setting up multicore cluster & generating molecule mapping tables ..."
[1] "Finished multi-threaded hamming distances"
[1] "Demultiplexing output bam file by cell barcode..."
[1] "Using python implementation to demultiplex."
[1] "2020-07-22 06:32:01 EDT"
[1] "Breaking up demultiplexing in 5 chunks. This may be because you have >10000 cells or a too low filehandle limit (ulimit -n)."
[1] "Demultiplexing zUMIs bam file..."
[1] "Demultiplexing complete."
[1] "2020-07-23 09:59:37 EDT"
[1] "Correcting UMI barcode tags..."
[1] "Creating sorted final bam file..."
[E::hts_open_format] Failed to open file /mnt/md0/MB/analyses/lev_mouse/Pipeline/09_rna_kinetics/velocyto/kp/zumis_180430_30dVhl123/zUMIs_output/demultiplexed/zumis_180430_30dVhl123.AGGTTCCCATAGCCCTTCGATT.demx.UBcorrected.bam
samtools merge: fail to open "/mnt/md0/MB/analyses/lev_mouse/Pipeline/09_rna_kinetics/velocyto/kp/zumis_180430_30dVhl123/zUMIs_output/demultiplexed/zumis_180430_30dVhl123.AGGTTCCCATAGCCCTTCGATT.demx.UBcorrected.bam": Too many open files
[1] "4.5e+08 Reads per chunk"
[E::hts_open_format] Failed to open file /mnt/md0/MB/analyses/lev_mouse/Pipeline/09_rna_kinetics/velocyto/kp/zumis_180430_30dVhl123/zumis_180430_30dVhl123.filtered.Aligned.GeneTagged.UBcorrected.sorted.bam
samtools index: failed to open "/mnt/md0/MB/analyses/lev_mouse/Pipeline/09_rna_kinetics/velocyto/kp/zumis_180430_30dVhl123/zumis_180430_30dVhl123.filtered.Aligned.GeneTagged.UBcorrected.sorted.bam": No such file or directory
[1] "2020-07-23 11:46:28 EDT"
[1] "Here are the detected subsampling options:"
[1] "Automatic downsampling"
[1] "Working on barcode chunk 1 out of 1"
[1] "Processing 25009 barcodes in this chunk..."
Error in value[[3L]](cond) : 
  failed to open BamFile: file(s) do not exist:
  ‘/mnt/md0/MB/analyses/lev_mouse/Pipeline/09_rna_kinetics/velocyto/kp/zumis_180430_30dVhl123/zumis_180430_30dVhl123.filtered.Aligned.GeneTagged.UBcorrected.sorted.bam’
Calls: reads2genes_new ... tryCatch -> tryCatchList -> tryCatchOne -> <Anonymous>
Execution halted
Thu Jul 23 11:46:29 EDT 2020
Loading required package: yaml
Loading required package: Matrix
[1] "loomR found"
Error in gzfile(file, "rb") : cannot open the connection
Calls: rds_to_loom -> readRDS -> gzfile
In addition: Warning message:
In gzfile(file, "rb") :
  cannot open compressed file '/mnt/md0/MB/analyses/lev_mouse/Pipeline/09_rna_kinetics/velocyto/kp/zumis_180430_30dVhl123/zUMIs_output/expression/zumis_180430_30dVhl123.dgecounts.rds', probable reason 'No such file or directory'
Execution halted
Thu Jul 23 11:46:32 EDT 2020
[1] "2020-07-23 11:46:32 EDT"
[1] "Preparing bam file for velocyto..."
[1] "2020-07-23 12:27:01 EDT"
[1] "Attempting to run RNA velocity..."
[1] "RNA velocity done!"
[1] "2020-07-23 15:43:48 EDT"
Descriptive statistics...
[1] "I am loading useful packages for plotting..."
[1] "2020-07-23 15:43:49 EDT"
Warning message:
In fread(gtf, select = 1:2, header = F) :
  Found and resolved improper quoting in first 100 rows. If the fields are not quoted (e.g. field separator does not appear within any field), try quote="" to avoid this warning.
Error in gzfile(file, "rb") : cannot open the connection
Calls: readRDS -> gzfile
In addition: Warning message:
In gzfile(file, "rb") :
  cannot open compressed file '/mnt/md0/MB/analyses/lev_mouse/Pipeline/09_rna_kinetics/velocyto/kp/zumis_180430_30dVhl123/zUMIs_output/expression/zumis_180430_30dVhl123.dgecounts.rds', probable reason 'No such file or directory'
Execution halted
Thu Jul 23 15:45:44 EDT 2020

**Desktop (please complete the following information):**
Ubuntu 1604
zUMI's v2.9.3b

help? Thanks!

**Comment by cziegenhain** [comment]
Hi,

Sorry that you are encountering this issue!
We recently parallelized the demultiplexing step to be faster, at the expense of more temporary intermediate files. zUMIs should clean these away though again later when it's running properly.

Can you tell me what your file handle limit is (`ulimit -n`). Ideally zUMIs should not use more FHs than allowed, but for now try to set a big higher filehandle limit (eg. `ulimit -n 50000`) ?

Best,
Christoph

**Comment by mbassalbioinformatics** [comment]
ulimit -n was set to 5120.  Ill try changing it to 500,000 and se how that goes.  Will update accordingly.... Thanks!

**Comment by mbassalbioinformatics** [comment]
Hi
Ive made the change but the pipeline seems to just sit at "[1] "Demultiplexing zUMIs bam file...""
Its been at that stage doing nothing for a couple of days now....

Also the demultiplexed folder has a crazy ~820,000 files. 

Am I missing something or doing something wrong to for it to stop here?  I didnt run into the same issue in previous versions of zumi's (cant remember which version unfortunately).  Attached is the yaml file for you if you need.

Thanks.
[zumis_180430_30dVhl123.txt](https://github.com/sdparekh/zUMIs/files/5047442/zumis_180430_30dVhl123.txt)

**Comment by cziegenhain** [comment]
Hi,

If you have the barcodes you want, you can always give a list of expected barcodes as a plain text file. 
https://github.com/sdparekh/zUMIs/wiki/Barcodes#barcode-annotation

For the issue of hanging, can you check which processes are causing this (eg stop) and whether they are still using CPU or just idle?

Best
C

**Comment by mbassalbioinformatics** [comment]
The processes are just idling.

Searching for zUMI's in my task list im seeing the following "running" but just idling
demultiplex_BC.py
R zumis-dge2.R (2 instances of this script running)
zumis.sh master script

Any suggestions?

**Comment by cziegenhain** [comment]
I pushed a slightly more conservative approach to the demultiplexing script.
How many cells do you have and how many threads are you giving zUMIs?

**Comment by mbassalbioinformatics** [comment]
Ok ill give the script a go over the weekend and let you know.

Im looking to pull out ~6-7K cells and giving the script 30 threads.

**Comment by mbassalbioinformatics** [comment]
Ok so the dataset that I contacted you about initially, that worked.  I tried zUMI's on a 2nd dataset but that still hangs at the demultiplexing stage however even with a ulimit of 65,000.

I did realize also that it was v2.4 that I used previously that worked like a charm for the demultiplexing.

So any further suggestions to try?

**Comment by cziegenhain** [comment]
The demultiplexing was switched to a pysam/python script in v2.6.3 or so. This should be faster but maybe less robust for you? 
How many barcodes are in the newest problematic dataset?
Trying to understand what leads it to stall like this.

**Comment by mbassalbioinformatics** [comment]
This dataset has 5 barcodes for 5 samples.  Total looking about 12-15K cells.

**Comment by cziegenhain** [comment]
Sorry I don't quite understand what you mean with 5 barcodes/samples and 15k cells?

**Comment by mbassalbioinformatics** [comment]
This is an indrop dataset, so each of the 5 samples is given an 8mer index in R3 in the library prep stage which is known to differentiate it from the other samples.  The remaining barcode information in R2 and R4 is random.  So samples are selected based on having the 8mer index of interest.  

So I know which indexes the 5 samples have, and they are the only samples worth pulling out basically. Everything else can be ignored.  Hope thats a little clearer?
[sequencing_indrops_libraries_02_28_18.pdf](https://github.com/sdparekh/zUMIs/files/5095240/sequencing_indrops_libraries_02_28_18.pdf)

**Comment by cziegenhain** [comment]
Oh okay I get it, thanks!

So if there is ~15k, zUMIs should be telling you something like this: "Breaking up demultiplexing in x chunks. This may be because you have >10000 cells or a too low filehandle limit (ulimit -n)." 
Does that happen?

If you want to try around a bit, you could try to force zUMIs to do the demultiplexing in more rounds with fewer open file handles per run by changing Line 383 in UMIstuffFUN.R (https://github.com/sdparekh/zUMIs/blob/main/UMIstuffFUN.R#L383)

`ceiling(nBCs/10000)` -> `ceiling(nBCs/5000)`

good luck,
Christoph

**Comment by mbassalbioinformatics** [comment]
Ok so I changed 
`ceiling(nBCs/10000)' -> 'ceiling(nBCs/3000)`

also setting 'ulimit -n 50000' or something similar clears the hang and allows things to complete just fine.

**Comment by cziegenhain** [comment]
Hey, 

Thanks for the feedback and glad that things run through fine.
I'll keep these issues in mind and try to optimize this step in future updates.

Best,
Christoph
