### ISSUE TITLE
error when running example data

### ISSUE THREAD

**Issue by yongjieliu** [sdparekh/zUMIs#38]
I run the command with suggested paraments and see this problem. 

`cut: $Path/zUMIs/ExampleData//chr22test.aligned.sorted.bam.ex.featureCounts: No such file or directory`
`Error in data.table::fread(paste("cut -f4 ", abamfile[2], ".featureCounts",  : 
File is empty: /tmp/RtmpTZ9xJh/file178a6f282ad2`
`Calls: makeGEprofile -> <Anonymous>
Execution halted`

the output directory contain chr22test.aligned.sorted.bam.featureCounts but without *.ex.featureCounts or *.in.featureCounts

**Comment by cziegenhain** [comment]
Hey,

Could you send me some more information on this?
- which operating system are you using?
- please paste the output of "ls -lh" for your working directory
- can you double check that you set the Path variable to a useful value? "ls $Path"
-

**Comment by yongjieliu** [comment]
Hi，
 I am using  CentOS release 6.4. The Path variable is useful.

The output files containg:
`-rw-rw-r-- 1 yjliu yjliu  47M May 31 19:56 chr22test.aligned.sorted.bam`
`-rw-rw-r-- 1 yjliu yjliu  53M May 31 20:16 chr22test.aligned.sorted.bam.featureCounts`
`-rw-rw-r-- 1 yjliu yjliu  78M May 31 19:56 chr22test.barcodelist.filtered.sort.sam`
`-rw-rw-r-- 1 yjliu yjliu 1.8K May 31 19:56 chr22test.Log.final.out`
`-rw-rw-r-- 1 yjliu yjliu  36K May 31 19:56 chr22test.Log.out`
`-rw-rw-r-- 1 yjliu yjliu  565 May 31 19:56 chr22test.Log.progress.out`
`-rw-rw-r-- 1 yjliu yjliu 672K May 31 19:56 chr22test.SJ.out.tab`
`drwx------ 2 yjliu yjliu 4.0K May 31 19:44 chr22test._STARgenome`
`drwx------ 2 yjliu yjliu   43 May 31 19:50 chr22test._STARpass1`
`drwxrwxr-x 5 yjliu yjliu   56 May 31 15:17 zUMIs_output`

**Comment by yongjieliu** [comment]
Hey,

I re-run the command in the ExampleData directory which containing test.aligned.sorted.bam.ex.featureCounts and test.aligned.sorted.bam.in.featureCounts files. And zUMIs works very well. 

But zUMIs can't built new test.aligned.sorted.bam.in.featureCounts and test.aligned.sorted.bam.ex.featureCounts files

the output files are showed below: 

`-rwxrwxr-x 1 yjliu yjliu  20M May 28 09:52 barcoderead_HEK.1mio.fq.gz`
`-rwxrwxr-x 1 yjliu yjliu  47M May 28 09:52 cDNAread_HEK.1mio.fq.gz`
`-rw-rw-r-- 1 yjliu yjliu  11K Jun  4 15:17 log.txt`
`-rw-rw-r-- 1 yjliu yjliu 3.6K Jun  4 15:17 Rplots.pdf`
`-rwxrwxr-x 1 yjliu yjliu  47M Jun  4 14:52 test.aligned.sorted.bam`
`-rwxrwxr-x 1 yjliu yjliu  51M May 28 09:52 test.aligned.sorted.bam.ex.featureCounts`
`-rw-rw-r-- 1 yjliu yjliu  53M Jun  4 15:15 test.aligned.sorted.bam.featureCounts`
`-rwxrwxr-x 1 yjliu yjliu  51M May 28 09:52 test.aligned.sorted.bam.in.featureCounts`
`-rwxrwxr-x 1 yjliu yjliu  78M Jun  4 14:52 test.barcodelist.filtered.sort.sam`
`-rwxrwxr-x 1 yjliu yjliu 1.8K Jun  4 14:52 test.Log.final.out`
`-rwxrwxr-x 1 yjliu yjliu  32K Jun  4 14:52 test.Log.out`
`-rwxrwxr-x 1 yjliu yjliu  447 Jun  4 14:52 test.Log.progress.out`
`-rw-r--r-- 1 yjliu yjliu  380 Jun  4 14:17 test.sh`
`-rwxrwxr-x 1 yjliu yjliu 672K Jun  4 14:52 test.SJ.out.tab`
`drwx------ 2 yjliu yjliu 4.0K Jun  4 14:43 test._STARgenome`
`drwx------ 2 yjliu yjliu   43 Jun  4 14:47 test._STARpass1`
`-rw-rw-r-- 1 yjliu yjliu 1.4K Jun  4 14:39 test.zUMIs_run.txt`
`drwxrwxr-x 5 yjliu yjliu   56 May 28 09:52 zUMIs_output`

**Comment by cziegenhain** [comment]
Hey,

Thanks for the additional information!
It seems that in your system, the "ln" command is missing. We use it to link the .ex and .in files!

Try to install it with your package manager, eg
yum install ln

That should solve the issue!

**Comment by yongjieliu** [comment]
Hey,

The "ln" command always works well. But the same zUMIs error still exit.

**Comment by sdparekh** [comment]
Hi, Can you send me version of your Rsubread package? Meanwhile, you could try to remove all the files and re-run the example data. It is strange to me that the featureCounts files for 'ex' and 'in' are generated but I don't see the bam files links.

**Comment by yongjieliu** [comment]
Hi, the featureCounts files for 'ex' and 'in' are downloaded in the zUMIs git project. The error is that zUMIs can't built new featureCounts files for 'ex' and 'in'.

I see the bam files links were cleaned by zUMIs

My Rsubread version 1.30.2

I re-run the example data and the output files are showed below:
`-rwxrwxr-x 1 yjliu yjliu  20M May 28 09:52 barcoderead_HEK.1mio.fq.gz`
`-rwxrwxr-x 1 yjliu yjliu  47M May 28 09:52 cDNAread_HEK.1mio.fq.gz`
`-rw-rw-r-- 1 yjliu yjliu  47M Jun  4 22:04 test.aligned.sorted.bam`
`-rw-rw-r-- 1 yjliu yjliu  53M Jun  4 22:30 test.aligned.sorted.bam.featureCounts`
`-rw-rw-r-- 1 yjliu yjliu  78M Jun  4 22:05 test.barcodelist.filtered.sort.sam`
`-rw-rw-r-- 1 yjliu yjliu 1.8K Jun  4 22:04 test.Log.final.out`
`-rw-rw-r-- 1 yjliu yjliu  32K Jun  4 22:04 test.Log.out`
`-rw-rw-r-- 1 yjliu yjliu  447 Jun  4 22:04 test.Log.progress.out`
`-rw-rw-r-- 1 yjliu yjliu 672K Jun  4 22:04 test.SJ.out.tab`
`drwx------ 2 yjliu yjliu 4.0K Jun  4 21:55 test._STARgenome`
`drwx------ 2 yjliu yjliu   43 Jun  4 21:59 test._STARpass1`
`-rw-rw-r-- 1 yjliu yjliu 1.4K Jun  4 21:44 test.zUMIs_run.txt`
`drwxrwxr-x 5 yjliu yjliu   56 Jun  4 21:44 zUMIs_output`

zUMI ERROR report:

[error.report.txt](https://github.com/sdparekh/zUMIs/files/2070641/error.report.txt)

**Comment by cziegenhain** [comment]
Hey,

I think we finally figured it out: Seems like the newest update of Rsubread::featureCounts (>1.30.x) has implemented new handling of input paths and resolves the symlink to the original file.
Thus, your zUMIs instance could not find the files in the correct path.

I have added a quick fix to zUMIs-dge.R, just replace that file and give it another go!

**Comment by cziegenhain** [comment]
Great! Let us know if you need anything else.

Best,
Christoph

**Comment by yueli711** [comment]
Hello, yongjieliu,

How can you figure out this question at last?

I have the same issue as yours.

Thank you in advance for your great help!

Best,

Yue
